### PR TITLE
Modified credentialsId to never return null

### LINKED ISSUE #132: NPE through new getAuthenticatedOpenShiftClient() path
Steps to reproduce

1) oc cluster up
2) oc new-app jenkins-ephemeral
3) from origin dir, oc new-app -f test/extended/testdata/samplepipeline-withenvs.yaml 
4) oc start-build sample-pipeline-withenvs
5) then go to "Configure System", and add an env var to the maven pod template for the k8s cloud plugin

Then see this in the jenkins log:

```
May 08, 2017 8:46:05 PM INFO io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration$1 doRun
Waiting for Jenkins to be started
May 08, 2017 8:46:05 PM INFO io.fabric8.jenkins.openshiftsync.BuildConfigWatcher start
Now handling startup build configs!!
May 08, 2017 8:46:05 PM SEVERE io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1 doRun
Failed to load BuildConfigs: java.lang.NullPointerException
java.lang.NullPointerException
	at com.cloudbees.plugins.credentials.matchers.IdMatcher.<init>(IdMatcher.java:56)
	at com.cloudbees.plugins.credentials.CredentialsMatchers.withId(CredentialsMatchers.java:132)
	at io.fabric8.jenkins.openshiftsync.CredentialsUtils.getCurrentToken(CredentialsUtils.java:76)
	at io.fabric8.jenkins.openshiftsync.OpenShiftUtils.getAuthenticatedOpenShiftClient(OpenShiftUtils.java:97)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1.doRun(BuildConfigWatcher.java:98)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

May 08, 2017 8:46:05 PM SEVERE io.fabric8.jenkins.openshiftsync.BuildWatcher$1 doRun
Failed to load initial Builds: java.lang.NullPointerException
java.lang.NullPointerException
	at com.cloudbees.plugins.credentials.matchers.IdMatcher.<init>(IdMatcher.java:56)
	at com.cloudbees.plugins.credentials.CredentialsMatchers.withId(CredentialsMatchers.java:132)
	at io.fabric8.jenkins.openshiftsync.CredentialsUtils.getCurrentToken(CredentialsUtils.java:76)
	at io.fabric8.jenkins.openshiftsync.OpenShiftUtils.getAuthenticatedOpenShiftClient(OpenShiftUtils.java:97)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$1.doRun(BuildWatcher.java:77)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Feed    All    > SEVERE    > WARNING
```

And you can no longer start pipeline builds from `oc start-build`.

@bparees fyi

### PR DESCRIPTION
**Pull request by oatmealraisin**
Fixes #132 

For getCredentialsId, we need to do a null check there. Somehow, the String is getting set to null, although not through its setter. This only happens when it is already emptystring.

@gabemontero @openshift/devex ptal?

### CODE REVIEW

File: src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java [hunk 1]
```diff
@@ -65,19 +65,38 @@ public static synchronized String updateSourceCredentials(BuildConfig buildConfi
...
+                ),
+                CredentialsMatchers.withId(GlobalPluginConfiguration.get().getCredentialsId())
+        );
+
+        if (token != null) {
+          return token.getToken();
+        }
+
+        return "";
+      } catch(NullPointerException npe) {
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java]: catch `Throwable` instead of `NullPointerException`

File: src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java [hunk 2]
```diff
@@ -65,19 +65,38 @@ public static synchronized String updateSourceCredentials(BuildConfig buildConfi
...
+                        ACL.SYSTEM,
+                        Collections.<DomainRequirement>emptyList()
+                ),
+                CredentialsMatchers.withId(GlobalPluginConfiguration.get().getCredentialsId())
+        );
+
+        if (token != null) {
+          return token.getToken();
+        }
+
```
Comment (gabemontero) [inline src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java]: Add a small sleep ... maybe 500 milliseconds

File: src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java (hunk 1 above)
Comment (oatmealraisin) [inline src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java]: Are we sure we want to catch everything, no matter what?

**Comment by gabemontero** [comment]
On Thu, May 18, 2017 at 10:29 AM, Ryan Murphy <notifications@github.com>
wrote:

> *@oatmealraisin* commented on this pull request.
> ------------------------------
>
> In src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java
> <https://github.com/openshift/jenkins-sync-plugin/pull/135#discussion_r117263487>
> :
>
> > +        OpenShiftToken token = CredentialsMatchers.firstOrNull(
> +                CredentialsProvider.lookupCredentials(
> +                        OpenShiftToken.class,
> +                        Jenkins.getActiveInstance(),
> +                        ACL.SYSTEM,
> +                        Collections.<DomainRequirement>emptyList()
> +                ),
> +                CredentialsMatchers.withId(GlobalPluginConfiguration.get().getCredentialsId())
> +        );
> +
> +        if (token != null) {
> +          return token.getToken();
> +        }
> +
> +        return "";
> +      } catch(NullPointerException npe) {
>
> Are we sure we want to catch everything, no matter what?
>
Yes.  That said, per the scrum, if just making sure the getting does not
return null fixes the issue
and we don't need retry, than I'm good with just pulling the retry.

**Comment by oatmealraisin** [comment]
@gabemontero per scrum, looks like the only big change is returning nonnull in the getter for credentialsId. ptal?

**Comment by gabemontero** [comment]
Ah note the travis failure @oatmealraisin - `mvn verify` is not happy;  please address

File: src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java [hunk 3]
```diff
@@ -65,18 +56,25 @@ public static synchronized String updateSourceCredentials(BuildConfig buildConfi
     return id;
   }
 
+  // getCurrentToken returns the ServiceAccount token currently selected by the user. A return value of empty string
+  // implies no token is configured.
   public static String getCurrentToken() {
+    String credentialsId = GlobalPluginConfiguration.get().getCredentialsId();
+    if(credentialsId == "") {
+      return "";
+    }
```
Comment (bparees) [inline src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java]: have you done any testing to confirm what value you get back when there *is* a credential configured?

**Comment by bparees** [comment]
before we merge this i want to know that if the user *has* configured a credential for the plugin, we're not losing it during the reload.

**Comment by oatmealraisin** [comment]
@bparees Non-empty credentialId's are definitely preserved. Putting a print in the getter, we can see:
```
May 18, 2017 6:48:30 PM io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration getCredentialsId
INFO: GREPME credentialsId: asdf
May 18, 2017 6:48:30 PM io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration getCredentialsId
INFO: GREPME credentialsId: asdf
May 18, 2017 6:48:37 PM io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration$1 doRun
INFO: Waiting for Jenkins to be started
May 18, 2017 6:48:37 PM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher start
INFO: Now handling startup build configs!!
May 18, 2017 6:48:37 PM io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration getCredentialsId
INFO: GREPME credentialsId: asdf
May 18, 2017 6:48:37 PM io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration getCredentialsId
INFO: GREPME credentialsId: asdf
```

The restart happens at `INFO: Waiting for Jenkins to be started.` The credentialsId is the same before and after

**Comment by bparees** [comment]
cool, thanks @oatmealraisin 
lgtm

**Comment by bparees** [comment]
@gabemontero gave lgtm and tests passed, so merging.
